// Generated by https://quicktype.io

export interface Certificado {
  id:               string;
  nombre:        string;
  detalle?:       DetalleCertificado[];
}

export interface DetalleCertificado{
  id: string;
  titulo: string;
  descripcion: string;
}


