// Generated by https://quicktype.io

export interface Matricula {
  id:               string;
  persona:        string;
  certificado:    string;
  nota?:   number;
  monto?: number;
  nombrePersona?:  string;
  nombreCertificado?: string;
}




