// Generated by https://quicktype.io

export interface Persona {
  id:               string;
  nombre:        string;
  colegio:        string;
  correo:        string;
  alt_img?:         string;
  nombreColegio?: string;
}


